<a href="https://colab.research.google.com/github/Damiscolusan/Automobile-eda-Project/blob/main/Data_Manipulation_with_Pandas%5BKrish_Nair%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

In [34]:
import datetime

start_date = np.datetime64('2023-01-01')
end_date = np.datetime64('2024-01-01')

timestamps = np.random.randint(
    start_date.astype('int64'),
    end_date.astype('int64'),
    size=1500
)

dates = pd.to_datetime(timestamps, unit='D').strftime('%Y-%m-%d')



print(dates[0:5])

Index(['2023-04-19', '2023-08-04', '2023-07-20', '2023-07-25', '2023-04-14'], dtype='object')

In [35]:
df= pd.DataFrame(
    {

     'Date':dates,
          'Category':np.random.choice(['A', 'B', 'C'], size=1500),
                  'Value':np.random.uniform(5, 140, size=1500), # uniform because we need float numbers
                          'Product':np.random.choice(['Prod1', 'Prod2', 'Prod3'], size=1500),
                                  'Sales':np.random.randint(550, 1500, size=1500),
                                        'Region':np.random.choice(['North','South', 'West', 'East'], size=1500)

     }

)

df.head()

         Date Category       Value Product  Sales Region
0  2023-04-19        C  109.981554   Prod3    773  South
1  2023-08-04        C   97.230412   Prod2    652   West
2  2023-07-20        C   56.150285   Prod1   1467  North
3  2023-07-25        C   80.500769   Prod2    656   East
4  2023-04-14        C   50.855389   Prod2    921   East

In [ ]:
# Introduce some null values into 'Value' and 'Sales' columns
np.random.seed(42) # for reproducibility
null_indices = np.random.choice(df.index, size=150, replace=False) # Choose 150 random indices
df.loc[null_indices, ['Value', 'Sales']] = np.nan

print("DataFrame with introduced null values:")
display(df.head())
print("\nNumber of null values per column after introduction:")
display(df.isnull().sum())

In [36]:
display(df.head())
print()
display(df.tail())

         Date Category       Value Product  Sales Region
0  2023-04-19        C  109.981554   Prod3    773  South
1  2023-08-04        C   97.230412   Prod2    652   West
2  2023-07-20        C   56.150285   Prod1   1467  North
3  2023-07-25        C   80.500769   Prod2    656   East
4  2023-04-14        C   50.855389   Prod2    921   East

            Date Category       Value Product  Sales Region
1495  2023-08-23        C  137.474131   Prod2   1173   East
1496  2023-07-04        A   65.481063   Prod1   1239  North
1497  2023-09-22        B   21.566895   Prod2    677   West
1498  2023-01-25        B  131.488565   Prod3   1473   East
1499  2023-12-05        C   40.412534   Prod3    970  North

In [37]:
df.isnull().any()

Date        False
Category    False
Value       False
Product     False
Sales       False
Region      False
dtype: bool

I want to introduce some null values into the df Dataframe

Parameter,  ---------> Description
- a,---------> "The array or integer from which to choose. If it's an integer, say N, it chooses from np.arange(N) (i.e., 0,1,2,...,N−1)."
- size,---------> "The number of random samples to return. If None (the default), - a single value is returned."
replace,--------->  Whether the sampling is done with replacement (True) or without replacement (False).
- p,------------>   "An array of probabilities (weights) associated with each element in a. If None, the selection is uniform (equal chance for all elements)."

In [38]:
np.random.seed(27)# for reproducability and to shuffle it
# np.random.choice is a function in the NumPy library that allows you to randomly select one or more elements from a specified array or sequence.

# It's essentially the digital equivalent of drawing items out of a hat.
null_values = np.random.choice(df.index, size=150)
df.loc[null_values,['Value','Sales']] = np.nan

display(df.head())

df.isnull().sum()

         Date Category       Value Product   Sales Region
0  2023-04-19        C  109.981554   Prod3   773.0  South
1  2023-08-04        C   97.230412   Prod2   652.0   West
2  2023-07-20        C   56.150285   Prod1  1467.0  North
3  2023-07-25        C   80.500769   Prod2   656.0   East
4  2023-04-14        C         NaN   Prod2     NaN   East

Date          0
Category      0
Value       145
Product       0
Sales       145
Region        0
dtype: int64

In [ ]:
data=sns.load_dataset('titanic')
data.head()

In [39]:
data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [17]:
df_filled =df.fillna(0)

In [40]:
# Filling missing values with the mean of the column
#Let's create a New Column
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

            Date Category       Value Product   Sales Region  Sales_fillNA
0     2023-04-19        C  109.981554   Prod3   773.0  South    773.000000
1     2023-08-04        C   97.230412   Prod2   652.0   West    652.000000
2     2023-07-20        C   56.150285   Prod1  1467.0  North   1467.000000
3     2023-07-25        C   80.500769   Prod2   656.0   East    656.000000
4     2023-04-14        C         NaN   Prod2     NaN   East   1027.276015
...          ...      ...         ...     ...     ...    ...           ...
1495  2023-08-23        C  137.474131   Prod2  1173.0   East   1173.000000
1496  2023-07-04        A   65.481063   Prod1  1239.0  North   1239.000000
1497  2023-09-22        B   21.566895   Prod2   677.0   West    677.000000
1498  2023-01-25        B  131.488565   Prod3  1473.0   East   1473.000000
1499  2023-12-05        C   40.412534   Prod3   970.0  North    970.000000

[1500 rows x 7 columns]

In [41]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [42]:
# 2. Rerun the problematic line, which will now work:
df = df.rename(columns={'Date':'Sales_Date'})
print(df.head())

   Sales_Date Category       Value Product   Sales Region  Sales_fillNA
0  2023-04-19        C  109.981554   Prod3   773.0  South    773.000000
1  2023-08-04        C   97.230412   Prod2   652.0   West    652.000000
2  2023-07-20        C   56.150285   Prod1  1467.0  North   1467.000000
3  2023-07-25        C   80.500769   Prod2   656.0   East    656.000000
4  2023-04-14        C         NaN   Prod2     NaN   East   1027.276015

In [44]:
# Change datatypes
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype('float')
df.head()

,Sales_Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new
0,2023-04-19,C,109.981554,Prod3,773.0,South,773.000000,109.981554
1,2023-08-04,C,97.230412,Prod2,652.0,West,652.000000,97.230412
2,2023-07-20,C,56.150285,Prod1,1467.0,North,1467.000000,56.150285
3,2023-07-25,C,80.500769,Prod2,656.0,East,656.000000,80.500769
4,2023-04-14,C,NaN,Prod2,NaN,East,1027.276015,71.079586

In [47]:
# To apply functions to a series or column
df['New_Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sales_Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New_Value
0,2023-04-19,C,109.981554,Prod3,773.0,South,773.000000,109.981554,219.963107
1,2023-08-04,C,97.230412,Prod2,652.0,West,652.000000,97.230412,194.460824
2,2023-07-20,C,56.150285,Prod1,1467.0,North,1467.000000,56.150285,112.300570
3,2023-07-25,C,80.500769,Prod2,656.0,East,656.000000,80.500769,161.001538
4,2023-04-14,C,NaN,Prod2,NaN,East,1027.276015,71.079586,NaN

In [48]:
# Data Aggregating and Grouping
df.head(3)

,Sales_Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New_Value
0,2023-04-19,C,109.981554,Prod3,773.0,South,773.0,109.981554,219.963107
1,2023-08-04,C,97.230412,Prod2,652.0,West,652.0,97.230412,194.460824
2,2023-07-20,C,56.150285,Prod1,1467.0,North,1467.0,56.150285,112.300570

In [49]:
#Mean of the Specific values of Products
# Format is      df.groupby('Categorical Value')[Ordinal/Continuous data] .mean() or mode or anything else
grouped_mean= df.groupby('Product')['Value']
grouped_mean

Find Average sales based on Product

In [53]:
#Mean of the Specific values of Products
# Format is      df.groupby('Categorical Value')[Ordinal/Continuous data] .mean() or mode or anything else
grouped_mean= df.groupby('Product')['Sales'].mean()
grouped_mean

Product
Prod1    1039.124183
Prod2    1015.087146
Prod3    1027.633867
Name: Sales, dtype: float64

Let's group by 2 different categorical variables

Find Total Sales and Average Sales based on Product and Region

In [55]:
grouped_sum = df.groupby(['Product','Region'])['Sales'].sum()
grouped_sum

Product  Region
Prod1    East      119404.0
         North     118008.0
         South     127162.0
         West      112384.0
Prod2    East      114023.0
         North     124428.0
         South     103368.0
         West      124106.0
Prod3    East      107433.0
         North     120658.0
         South     112985.0
         West      108000.0
Name: Sales, dtype: float64

In [58]:
grouped_avg = df.groupby(['Product','Region'])['Sales'].mean()
grouped_avg

Product  Region
Prod1    East      1075.711712
         North     1026.156522
         South     1033.837398
         West      1021.672727
Prod2    East      1027.234234
         North      972.093750
         South     1033.680000
         West      1034.216667
Prod3    East      1004.046729
         North     1049.200000
         South     1036.559633
         West      1018.867925
Name: Sales, dtype: float64

Aggregate Multiple Functions

In [60]:
df = df.rename(columns={'Value':'Product_Value_Rate'})
print(df.head())

   Sales_Date Category  Product_Value_Rate Product   Sales Region  \
0  2023-04-19        C          109.981554   Prod3   773.0  South
1  2023-08-04        C           97.230412   Prod2   652.0   West
2  2023-07-20        C           56.150285   Prod1  1467.0  North
3  2023-07-25        C           80.500769   Prod2   656.0   East
4  2023-04-14        C                 NaN   Prod2     NaN   East

   Sales_fillNA   Value_new   New_Value
0    773.000000  109.981554  219.963107
1    652.000000   97.230412  194.460824
2   1467.000000   56.150285  112.300570
3    656.000000   80.500769  161.001538
4   1027.276015   71.079586         NaN

In [61]:
grouped_agg=df.groupby('Region')['Product_Value_Rate'].agg(['mean','sum', 'count'])
grouped_agg

             mean           sum  count
Region
East    69.202278  22767.549390    329
North   72.551907  25973.582575    358
South   71.392468  23702.299439    332
West    71.039905  23869.408067    336

## Merging and Joining DataFrames

In [63]:
df1 = pd.DataFrame({'Key':['A', 'B', 'C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A', 'B', 'D'], 'Value1':[4,5,6]})

In [64]:
display('df1', df1)
print()
display('df2', df2)

'df1'

  Key  Value1
0   A       1
1   B       2
2   C       3

'df2'

  Key  Value1
0   A       4
1   B       5
2   D       6

Merge DataFrames on 'Key Columns'

In [69]:
#Inner join is like intersection
# inner means from left to right at Matching key columns
pd.merge(df1, df2, on='Key', how='inner')

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [67]:
#Outer join is like Union
pd.merge(df1, df2, on='Key', how='outer')

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [70]:
# For the Left join the left DataFrame is given more priority than the right DataFrame
pd.merge(df1, df2, on='Key', how='left')# like left outer join

  Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [71]:
# For the Right join the left DataFrame is given more priority than the left DataFrame
pd.merge(df1, df2, on='Key', how='right')# like right outer join

  Key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6